// One-shot generator: decode all storage codes via CUDA __nv_fp* types.
// Build: g++ -O2 -std=c++17 -I/usr/local/cuda/include generate_nvidia_codec_goldens.cpp -o generate_nvidia_codec_goldens
#include <cuda_fp8.h>
#include <cuda_fp4.h>
#include <cmath>
#include <cstdio>
#include <limits>

static void print_float(float v) {
    if (std::isnan(v)) {
        std::printf("float('nan')");
    } else if (std::isinf(v)) {
        std::printf("float('%sinf')" , v < 0 ? "-" : "");
    } else {
        // Use hex float for exact round-trip where possible, else %.17g
        std::printf("%.17g", static_cast<double>(v));
    }
}

template <typename T>
static float decode_u8(unsigned char code) {
    T x;
    x.__x = code;
    return static_cast<float>(x);
}

static float decode_e2m1(unsigned char code) {
    __nv_fp4_e2m1 x;
    x.__x = code & 0x0f;
    return static_cast<float>(x);
}

int main() {
    std::printf("# Auto-generated by scripts/generate_nvidia_codec_goldens.cpp\n");
    std::printf("# Do not edit by hand; regenerate on a machine with CUDA fp4/fp8 headers.\n");
    std::printf("\"\"\"NVIDIA CUDA __nv_fp* decode goldens (storage code -> float).\"\"\"\n\n");

    std::printf("E2M1_GOLDEN = [\n");
    for (int i = 0; i < 16; ++i) {
        std::printf("    ");
        print_float(decode_e2m1(static_cast<unsigned char>(i)));
        std::printf(",  # code %d\n", i);
    }
    std::printf("]\n\n");

    std::printf("E4M3_GOLDEN = [\n");
    for (int i = 0; i < 256; ++i) {
        std::printf("    ");
        print_float(decode_u8<__nv_fp8_e4m3>(static_cast<unsigned char>(i)));
        std::printf(",  # code %d\n", i);
    }
    std::printf("]\n\n");

    std::printf("E5M2_GOLDEN = [\n");
    for (int i = 0; i < 256; ++i) {
        std::printf("    ");
        print_float(decode_u8<__nv_fp8_e5m2>(static_cast<unsigned char>(i)));
        std::printf(",  # code %d\n", i);
    }
    std::printf("]\n\n");

    std::printf("E8M0_GOLDEN = [\n");
    for (int i = 0; i < 256; ++i) {
        std::printf("    ");
        print_float(decode_u8<__nv_fp8_e8m0>(static_cast<unsigned char>(i)));
        std::printf(",  # code %d\n", i);
    }
    std::printf("]\n");
    return 0;
}
